import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Form from "../components/form";
import Results from "../components/results";

import { useState } from "react";

export default function Home() {
  const [result, setResult] = useState(null);
  console.log({ result });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to </h1>
        <h1 className={styles.rainbowText}>Random Coding Issues</h1>

        <Form setResult={setResult} />
        {result && <Results result={result} />}
        <div className={styles.grid}>
          <a href="https://github.com/tannerbyers/randomcodingissue" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Read more about the how and why of this website.</p>
          </a>

          <a href="https://github.com/tannerbyers/randomcodingissue" className={styles.card}>
            <h2>Code &rarr;</h2>
            <p>Check out the code that makes this site possible and maybe make your own version!</p>
          </a>

         
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
